version: "3.1"
services:

  discovery:
    image: bkake/discovery-service
    ports:
      - "8761:8761"
    networks:
      - backend

  category-service:
    image: bkake/category-service
    ports:
      - "8181:8181"
    depends_on:
      - discovery
      - zipkin
    networks:
      - backend
    env_file:
      - ./eureka.env
      - ./zipkin.env

  author-service:
    image: bkake/author-service
    ports:
      - "8282:8282"
    depends_on:
      - discovery
      - zipkin
    networks:
      - backend
    env_file:
      - ./eureka.env
      - ./zipkin.env

  new-service:
    image: bkake/new-service
    ports:
      - "8383:8383"
    depends_on:
      - discovery
      - zipkin
    networks:
      - backend
    env_file:
      - ./eureka.env
      - ./zipkin.env

  gateway:
    image: bkake/gateway-service
    ports:
      - "8762:8762"
    depends_on:
      - discovery
      - zipkin
      - category-service
      - author-service
      - new-service
    networks:
      - backend
    env_file:
      - ./eureka.env
      - ./zipkin.env

  zipkin:
    image: bkake/zipkin-service
    ports:
      - "9411:9411"
    depends_on:
      - discovery
    networks:
      - backend
    env_file:
      - ./eureka.env

  hystrix-dashboard:
    image: bkake/hystrix-dashboard
    ports:
      - "8763:8763"
    depends_on:
      - discovery
    networks:
      - backend
    env_file:
      - ./eureka.env

  admin-dashboard:
    image: bkake/admin-dashboard
    ports:
      - "8764:8764"
    depends_on:
      - discovery
    networks:
      - backend
    env_file:
      - ./eureka.env

networks:
  backend:
    driver: bridge