version: "3.1"
services:

  discovery:
    image: bkake/discovery-service
    ports:
      - "8761:8761"

  category-service:
    image: bkake/category-service
    ports:
      - "8181:8181"
    depends_on:
      - "discovery"
      - "zipkin"
    env_file:
      - ./eureka.env

  author-service:
    image: bkake/author-service
    ports:
      - "8282:8282"
    depends_on:
      - "discovery"
      - "zipkin"
    env_file:
      - ./eureka.env

  new-service:
    image: bkake/new-service
    ports:
      - "8383:8383"
    depends_on:
      - "category-service"
      - "author-service"
    env_file:
      - ./eureka.env

  gateway:
    image: bkake/gateway-service
    ports:
      - "8762:8762"
    depends_on:
      - "new-service"
    env_file:
      - ./eureka.env

  zipkin:
    image: bkake/zipkin-service
    ports:
      - "9411:9411"
