version: "3.1"
services:
  config-service:
     image: bkake/config-service
     ports:
       - "8888:8888"
     env_file:
       - ./gitconf.env
     networks:
       - backend
networks:
  backend:
    driver: bridge