version: "3.1"
services:
  config-service:
     image: bkake/config-service
     restart: always
     ports:
       - "8888:8888"
     env_file:
       - ./gitconf.env
     networks:
       - backend

  discovery:
    image: bkake/discovery-service
    restart: always
    ports:
      - "8761:8761"
    depends_on:
      - config-service
    networks:
      - backend
    env_file:
      - ./config.env

  category-service:
    image: bkake/category-service
    restart: always
    ports:
      - "8181:8181"
    depends_on:
      - config-service
      - discovery
      - zipkin
    networks:
      - backend
    env_file:
      - ./eureka.env
      - ./zipkin.env
      - ./config.env

  author-service:
    image: bkake/author-service
    restart: always
    ports:
      - "8282:8282"
    depends_on:
      - config-service
      - discovery
      - zipkin
    networks:
      - backend
    env_file:
      - ./eureka.env
      - ./zipkin.env
      - ./config.env

  new-service:
    image: bkake/new-service
    restart: always
    ports:
      - "8383:8383"
    depends_on:
      - config-service
      - discovery
      - zipkin
    networks:
      - backend
    env_file:
      - ./eureka.env
      - ./zipkin.env
      - ./config.env

  gateway:
    image: bkake/gateway-service
    restart: always
    ports:
      - "8762:8762"
    depends_on:
      - config-service
      - discovery
      - zipkin
      - category-service
      - author-service
      - new-service
    networks:
      - backend
    env_file:
      - ./eureka.env
      - ./zipkin.env
      - ./config.env

  zipkin:
    image: bkake/zipkin-service
    restart: always
    ports:
      - "9411:9411"
    depends_on:
      - config-service
      - discovery
    networks:
      - backend
    env_file:
      - ./eureka.env
      - ./config.env

  hystrix-dashboard:
    image: bkake/hystrix-dashboard
    restart: always
    ports:
      - "8763:8763"
    depends_on:
      - config-service
      - discovery
    networks:
      - backend
    env_file:
      - ./eureka.env
      - ./config.env

  admin-dashboard:
    image: bkake/admin-dashboard
    restart: always
    ports:
      - "8764:8764"
    depends_on:
      - config-service
      - discovery
    networks:
      - backend
    env_file:
      - ./eureka.env
      - ./config.env

networks:
  backend:
    driver: bridge