server:
  port: 8762
spring:
  application:
      name: gateway-service
      logging:
        level:
          org.springframework: WARN
          org.hibernate: WARN
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}

ribbon:
  eureka:
    enabled: true

management:
  security:
    enabled: false

zuul:
  routes:
    news:
      path: /news/**
      serviceId: new-service
      stripPrefix: false
    author:
      path: /authors/**
      serviceId: author-service
      stripPrefix: false
    category:
      path: /categories/**
      serviceId: category-service
      stripPrefix: false