server:
  port: 8762
spring:
  application:
      name: gateway-service
      logging:
        level:
          org.springframework: WARN
          org.hibernate: WARN
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    registerWithEureka: false

ribbon:
  eureka:
    enabled: true

management:
  security:
    enabled: false

zuul:
  routes:
    new:
      path: /news/**
      serviceId: new-service
      stripPrefix: false
    author:
      path: /authors/**
      serviceId: author-service
      stripPrefix: false
    category:
      path: /categories/**
      serviceId: category-service
      stripPrefix: false


