server:
  port: 8761

spring:
  application:
    name: discovery-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  security:
    enabled: false
