server:
  port: 8761

spring:
  application:
    name: discovery-service
  boot:
    admin:
      context-path: /admin
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: true

management:
  security:
    enabled: false
