server:
  port: 8181

spring:
  application:
    name: category-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: jdbc:h2:mem:category-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

ribbon:
  eureka:
    enabled: true

management:
  security:
    enabled: false