server:
  port: ${PORT:8181}

spring:
  application:
    name: category-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN
  datasource:
    url: jdbc:h2:mem:category-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}

ribbon:
  eureka:
    enabled: true