server:
  port: 8383

spring:
  application:
    name: new-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN
  datasource:
    url: jdbc:h2:mem:new-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

ribbon:
  eureka:
    enabled: true