server:
  port: ${PORT:8383}

spring:
  application:
    name: new-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN
  datasource:
    url: jdbc:h2:mem:new-db
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10