FROM openjdk:8-jre-alpine
MAINTAINER Bangaly KAKE <bangaly.kake@gmail.com>
COPY ./target/category-service-1.0-SNAPSHOT.jar /app/
WORKDIR /app/
EXPOSE 8181
CMD ["java", "-jar", "category-service-1.0-SNAPSHOT.jar"]

